// Generated by gencpp from file vape_msgs/Path.msg
// DO NOT EDIT!


#ifndef VAPE_MSGS_MESSAGE_PATH_H
#define VAPE_MSGS_MESSAGE_PATH_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vape_msgs
{
template <class ContainerAllocator>
struct Path_
{
  typedef Path_<ContainerAllocator> Type;

  Path_()
    : i(0)  {
    }
  Path_(const ContainerAllocator& _alloc)
    : i(0)  {
  (void)_alloc;
    }



   typedef uint32_t _i_type;
  _i_type i;





  typedef boost::shared_ptr< ::vape_msgs::Path_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vape_msgs::Path_<ContainerAllocator> const> ConstPtr;

}; // struct Path_

typedef ::vape_msgs::Path_<std::allocator<void> > Path;

typedef boost::shared_ptr< ::vape_msgs::Path > PathPtr;
typedef boost::shared_ptr< ::vape_msgs::Path const> PathConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vape_msgs::Path_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vape_msgs::Path_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vape_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'vape_msgs': ['/home/Robocar/stack/src/vape_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vape_msgs::Path_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vape_msgs::Path_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vape_msgs::Path_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vape_msgs::Path_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vape_msgs::Path_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vape_msgs::Path_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vape_msgs::Path_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fe8f8503cfe379ff4fb978ea4ca6f246";
  }

  static const char* value(const ::vape_msgs::Path_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfe8f8503cfe379ffULL;
  static const uint64_t static_value2 = 0x4fb978ea4ca6f246ULL;
};

template<class ContainerAllocator>
struct DataType< ::vape_msgs::Path_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vape_msgs/Path";
  }

  static const char* value(const ::vape_msgs::Path_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vape_msgs::Path_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 i\n\
";
  }

  static const char* value(const ::vape_msgs::Path_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vape_msgs::Path_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.i);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Path_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vape_msgs::Path_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vape_msgs::Path_<ContainerAllocator>& v)
  {
    s << indent << "i: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.i);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VAPE_MSGS_MESSAGE_PATH_H
